name: look

environment:
  sdk: ">=2.18.0 <4.0.0"

packages:
  - example
  - look
  - look/example
  - look_generator
  - look_generator/example

scripts:
  analyze:
    exec: flutter analyze
    description: Analyze the project
  build_runner:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    description: Run build_runner build
  format:
    exec: dart format .
    description: Formatting files
  check_format:
    exec: dart format --set-exit-if-changed .
    description: Check formatting
  test:
    exec: flutter test --dart-define=golden_tolerance=1
    description: Run tests
  golden:
    exec: flutter test --update-goldens
    description: Update Golden files
  upgrade:
    exec: flutter pub upgrade --major-versions
    description: Upgrade dependencies
  fix:
    exec: dart fix --apply
    description: Apply Dart fix