targets:
  $default:
    builders:
      look_builder:
        enabled: true
      golden_builder:
        enabled: true

builders:
  look_builder:
    import: 'package:look_generator/builder.dart'
    builder_factories: ['lookBuilder']
    build_extensions: { '.dart': ['.look.dart'] }
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for:
        # Only apply to .dart files in the lib directory
        include:
        - lib/**
  golden_builder:
    import: 'package:look_generator/builder.dart'
    builder_factories: ['goldenBuilder']
    build_extensions: { '.dart': ['.look.dart'] }
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for:
        # Only apply to .dart files in the test directory
        include:
        - test/**