name: CI
on: push

jobs:
  build-look:
    name: Build example app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
      - name: Build Watchers package
        run: |
          cd look
          flutter pub get
          flutter analyze
          flutter format --set-exit-if-changed .
          flutter test
  build-look_generator:
    needs: build-look
    name: Build example app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
      - name: Build Watchers package
        run: |
          cd example
          flutter pub get
          flutter analyze
          flutter format --set-exit-if-changed .
          flutter test
  build-example:
    needs: build-look_generator
    name: Build example app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
      - name: Build Watchers package
        run: |
          cd example
          flutter pub get
          flutter analyze
          flutter format --set-exit-if-changed .
          flutter test
          flutter pub run build_runner build --delete-conflicting-outputs