name: CI
on: push

jobs:
  sanity-check:
    name: Perform checks with melos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
      - name: Check warnings, format and tests
        run: |
          dart pub global activate melos
          melos bs
          melos run analyze
          melos run check_format
          melos run test
  build-web:
    needs: sanity-check
    name: Build web
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [example, look/example]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
      - name: Build web
        run: |
          cd ${{ matrix.directory }}
          flutter build web